apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "cronjob.fullname" . }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          serviceAccountName: {{ include "cronjob.serviceAccountName" . }}
          containers:
          - name: {{ include "cronjob.fullname" . }}
            image: "{{ .Values.image.repository }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            volumeMounts:
              {{- include "cronjob.volumeMounts" . | nindent 12 }}
            {{- with .Values.commandOverride }}
            command:
              {{- toYaml .| nindent 12  }}
            {{- end }}
            resources:
            {{- toYaml .Values.resources | nindent 12 }}
          restartPolicy: OnFailure
          volumes:
            {{- include "cronjob.volumes" . | nindent 10 }}

          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
