apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "grpc.fullname" . }}
spec:
  hosts: {{ .Values.gateway.hosts }}
  gateways:
    - {{ include "grpc.fullname" . }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "grpc.fullname" . }} # use grpc name 
            port:
              number: {{ .Values.grpc.port }}      
      corsPolicy:
        allowOrigin:
          - "*"
        allowMethods:
          - POST
          - GET
          - OPTIONS
        allowHeaders:
          - "*"  
        allowCredentials: false        