{{- if .Values.gateway.enabled -}}

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "bluegreen.fullname" . }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts: 
        {{- toYaml .Values.gateway.hosts | nindent 8 }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "bluegreen.fullname" . }}
spec:
  hosts: 
    {{- toYaml .Values.gateway.hosts | nindent 6 }}
  gateways:
    - {{ include "bluegreen.fullname" . }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "bluegreen.fullname" . }} # use bluegreen name 
            port:
              number: {{ .Values.service.port }}
      webbluegreenUpgrade: true  
      corsPolicy:
        allowOrigin:
          - "*"
        allowMethods:
          - POST
          - GET
          - OPTIONS
        allowHeaders:
          - "*"  
        allowCredentials: false        
{{- end }}