{{- if .Values.grpcAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "grpc.grpcAccountName" . }}
  labels:
    {{- include "grpc.labels" . | nindent 4 }}
  {{- with .Values.grpcAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 8 }}
{{- end }}
{{- end }}
