apiVersion: v1
kind: Service
metadata:
  name: {{ include "grpc.fullname" . }}
  labels:
    {{- include "grpc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http2

    - name: http2
      port: { { .Values.service.grpcport } }
      protocol: TCP
      targetPort: { { .Values.service.grpcport } }
  selector:
    {{- include "grpc.selectorLabels" . | nindent 4 }}
