apiVersion: v1
kind: Service
metadata:
  name: {{ include "grpc.fullname" . }}
  labels:
    {{- include "grpc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.grpc.type }}
  ports:
    - port: {{ .Values.grpc.port }}
      targetPort: http2
      protocol: TCP
      name: http
  selector:
    {{- include "login.selectorLabels" . | nindent 4 }}
