apiVersion: v1
kind: Service
metadata:
  name: {{ include "grpc.fullname" . }}
  labels:
    {{- include "grpc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.grpc.type }}
  ports:
    - port: {{ .Values.grpc.port }}
      targetPort: {{ .Values.grpc.port }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "grpc.selectorLabels" . | nindent 4 }}
