apiVersion: v1
kind: Service
metadata:
  name: {{ include "grpc.fullname" . }}
  labels:
    {{- include "grpc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http2
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "grpc.selectorLabels" . | nindent 4 }}
