apiVersion: v1
kind: Service
metadata:
  name: {{ include "login.fullname" . }}
  labels:
    {{- include "login.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    # - port: {{ .Values.service.port }}
    #   targetPort: http
    #   protocol: TCP
    #   name: http
    # - port: {{ .Values.service.grpcport }}
    #   targetPort: grpc
    #   protocol: TCP
    #   name: grpc


  {{- if not .Values.gateway.enabled }}
    - name: http2
      port: {{ .Values.service.grpcport }}
      protocol: TCP
      targetPort: {{ .Values.service.grpcport }}
  {{- end }}

  {{- if .Values.gateway.enabled }}
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  {{- end }}
  selector:
    {{- include "login.selectorLabels" . | nindent 4 }}
