{{- if .Values.volume.enabled }}
{{- $name := include "service.name" .}}
{{- range $key,$value := .Values.volume.options }}
{{- $size := .Values.volume.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ $name }}-{{ $value.name }}-{{ $key }}"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ $value.name }}
  resources:
    requests:
      storage: {{ $size }}
{{- end }}
{{- end }}