{{- if .Values.gateway.enabled -}}

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "socket.fullname" . }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: PASSTHROUGH
      hosts: {{ .Values.gateway.hosts }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "socket.fullname" . }}
spec:
  hosts: {{ .Values.gateway.hosts }}
  gateways:
    - {{ include "socket.fullname" . }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "socket.fullname" . }} # use socket name 
            port:
              number: {{ .Values.service.port }}
      websocketUpgrade: true  
      corsPolicy:
        allowOrigin:
          - "*"
        allowMethods:
          - POST
          - GET
          - OPTIONS
        allowHeaders:
          - "*"  
        allowCredentials: false        
{{- end }}
