{{- if .Values.volume.enabled }}
{{- range .Values.volume.options}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.name}}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .scname }}
  resources:
    requests:
      storage: 5Gi
{{- end }}
{{- end }}
